export const RECIEVE_DEALS = 'RECIEVE_DEALS';
export const RECIEVE_VOUCHERS = 'RECIEVE_VOUCHERS';
export const RECIEVE_FILTERS = 'RECIEVE_FILTERS';

export const TOGGLE_FILTER = 'TOGGLE_FILTER';

export const LOAD_TOUR = 'LOAD_TOUR';
export const VIEW_TOUR = 'VIEW_TOUR';

export const SET_ACTIVE_VOUCHER = 'SET_ACTIVE_VOUCHER';
